/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Threads.RazeThread;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dam
 */
public class InitialPanel extends javax.swing.JPanel {

    private MotorcycleFrame myFrame;
    private RazeThread runner1Thread;
    private RazeThread runner2Thread;
    private ArrayList<RazeThread> listaHilos;
    private Boolean terminar;

    /**
     * Creates new form PanelInicial
     */
    public InitialPanel(MotorcycleFrame myFrame) {
        initComponents();

        this.myFrame = myFrame;
        this.listaHilos = new ArrayList<RazeThread>();
        this.terminar = true;

        lblVueltas1.setText("");
        lblVueltas2.setText("");
        lblGanador1.setText("");
        lblGanador2.setText("");

        lblAccidente1.setVisible(false);
        lblAccidente2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressRunner2 = new javax.swing.JProgressBar();
        progressRunner1 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAccidente1 = new javax.swing.JLabel();
        lblAccidente2 = new javax.swing.JLabel();
        lblVueltas1 = new javax.swing.JLabel();
        lblVueltas2 = new javax.swing.JLabel();
        lblGanador1 = new javax.swing.JLabel();
        lblGanador2 = new javax.swing.JLabel();

        progressRunner2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressRunner2MouseClicked(evt);
            }
        });

        progressRunner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressRunner1MouseClicked(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnLeave.setText("Leave");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("RAZE");

        lblAccidente1.setText("Ha tenido un accidente :(");

        lblAccidente2.setText("Ha tenido un accidente :(");

        lblVueltas1.setText("jLabel2");

        lblVueltas2.setText("jLabel2");

        lblGanador1.setText("jLabel2");

        lblGanador2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnStart)
                                        .addGap(72, 72, 72)
                                        .addComponent(btnPause))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnLeave))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lblAccidente2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblAccidente1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(progressRunner2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblVueltas1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGanador2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(progressRunner1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblVueltas2)
                                    .addGap(36, 36, 36)
                                    .addComponent(lblGanador1))))))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblAccidente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressRunner1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVueltas2)
                            .addComponent(lblGanador1))
                        .addGap(40, 40, 40)))
                .addComponent(lblAccidente2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressRunner2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVueltas1)
                            .addComponent(lblGanador2))
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnPause))
                .addGap(26, 26, 26)
                .addComponent(btnLeave)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        iniciarCarrera();
    }//GEN-LAST:event_btnStartActionPerformed

    public void iniciarCarrera() {
        if (getTerminar()) {
            this.listaHilos = new ArrayList<RazeThread>();
            lblVueltas1.setText("");
            lblVueltas2.setText("");
            lblGanador1.setText("");
            lblGanador2.setText("");

            this.setTerminar(false);
            runner1Thread = new RazeThread(progressRunner1, listaHilos, lblVueltas1, lblGanador1, lblAccidente1, this);
            runner2Thread = new RazeThread(progressRunner2, listaHilos, lblVueltas2, lblGanador2, lblAccidente2, this);

            runner1Thread.start();
            runner2Thread.start();
        } else {
            try {
                setTerminar(true);
                Thread.sleep(70);
                iniciarCarrera();
            } catch (InterruptedException ex) {
                Logger.getLogger(InitialPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public Boolean getTerminar() {
        return this.terminar;
    }

    public void setTerminar(Boolean value) {
        this.terminar = value;
    }

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        if (runner1Thread.getDetenido()) {
            runner1Thread.setDetenidoFalse();
        } else {
            runner1Thread.setDetenidoTrue();
        }

        if (runner2Thread.getDetenido()) {
            btnPause.setText("Pause");
            runner2Thread.setDetenidoFalse();
        } else {
            btnPause.setText("Continue");
            runner2Thread.setDetenidoTrue();
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void progressRunner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressRunner1MouseClicked
        if (!lblAccidente1.isVisible() && !lblAccidente2.isVisible()) {
            if (runner1Thread.getDetenido()) {
                runner1Thread.setDetenidoFalse();
            } else {
                runner1Thread.setDetenidoTrue();
            }
        }
    }//GEN-LAST:event_progressRunner1MouseClicked

    private void progressRunner2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressRunner2MouseClicked
        if (!lblAccidente1.isVisible() && !lblAccidente2.isVisible()) {
            if (runner2Thread.getDetenido()) {
                runner2Thread.setDetenidoFalse();
            } else {
                runner2Thread.setDetenidoTrue();
            }
        }
    }//GEN-LAST:event_progressRunner2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccidente1;
    private javax.swing.JLabel lblAccidente2;
    private javax.swing.JLabel lblGanador1;
    private javax.swing.JLabel lblGanador2;
    private javax.swing.JLabel lblVueltas1;
    private javax.swing.JLabel lblVueltas2;
    private javax.swing.JProgressBar progressRunner1;
    private javax.swing.JProgressBar progressRunner2;
    // End of variables declaration//GEN-END:variables
}
