/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import Threads.RazeThread;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dam
 */
public class InitialPanel extends javax.swing.JPanel {
    private MotorcycleFrame myFrame;
    private RazeThread runner1Thread;
    private RazeThread runner2Thread;
    private ArrayList<RazeThread> listaHilos;
    private Boolean detenido;
    private Boolean terminar;
    
    /**
     * Creates new form PanelInicial
     */
    public InitialPanel(MotorcycleFrame myFrame) {
        initComponents();
        
        this.myFrame = myFrame;
        this.listaHilos = new ArrayList<RazeThread>();
        this.terminar = true;
        this.detenido = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressRunner2 = new javax.swing.JProgressBar();
        progressRunner1 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVueltas1 = new javax.swing.JLabel();
        lblVueltas2 = new javax.swing.JLabel();
        lblGanador1 = new javax.swing.JLabel();
        lblGanador2 = new javax.swing.JLabel();

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnLeave.setText("Leave");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("RAZE");

        lblGanador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblGanador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnStart)
                        .addGap(72, 72, 72)
                        .addComponent(btnPause))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnLeave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(progressRunner2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVueltas2)
                                .addGap(18, 18, 18)
                                .addComponent(lblGanador2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVueltas1)
                                .addGap(18, 18, 18)
                                .addComponent(lblGanador1)))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(progressRunner1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(progressRunner2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVueltas1)
                            .addComponent(lblGanador1))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVueltas2)
                            .addComponent(lblGanador2))))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnPause))
                .addGap(26, 26, 26)
                .addComponent(btnLeave)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(progressRunner1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        iniciarCarrera();
    }//GEN-LAST:event_btnStartActionPerformed

    public void iniciarCarrera() {
        if (getTerminar()) {
            this.listaHilos = new ArrayList<RazeThread>();
            lblVueltas1.setText("");
            lblVueltas2.setText("");
            lblGanador1.setText("");
            lblGanador2.setText("");

            this.setTerminar(false);
            runner1Thread = new RazeThread(progressRunner1, listaHilos, lblVueltas1, lblGanador1, this);
            runner2Thread = new RazeThread(progressRunner2, listaHilos, lblVueltas2, lblGanador2, this);

            runner1Thread.start();
            runner2Thread.start();
        }
        else {
            try {
                setTerminar(true);
                Thread.sleep(70);
                iniciarCarrera();
            } catch (InterruptedException ex) {
                Logger.getLogger(InitialPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public Boolean getDetenido() {
        return this.detenido;
    }
    
    public void setDetenido(Boolean value) {
        this.detenido = value;
    }
    
    public Boolean getTerminar() {
        return this.terminar;
    }
    
    public void setTerminar(Boolean value) {
        this.terminar = value;
    }
    
    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        if (this.getDetenido()) {
            btnPause.setText("Continue");
            this.setDetenido(false);
        }
        else {
            btnPause.setText("Pause");
            this.setDetenido(true);
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLeaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGanador1;
    private javax.swing.JLabel lblGanador2;
    private javax.swing.JLabel lblVueltas1;
    private javax.swing.JLabel lblVueltas2;
    private javax.swing.JProgressBar progressRunner1;
    private javax.swing.JProgressBar progressRunner2;
    // End of variables declaration//GEN-END:variables
}
